"""removed bio

Revision ID: 886bec1342f4
Revises: 5ba73f33c7b2
Create Date: 2024-08-01 15:03:07.026690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886bec1342f4'
down_revision = '5ba73f33c7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.VARCHAR(length=250), nullable=True))

    # ### end Alembic commands ###
